// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: meta.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	meta.proto

It has these top-level messages:
	Data
	NodeInfo
	DatabaseInfo
	RetentionPolicySpec
	RetentionPolicyInfo
	ShardGroupInfo
	ShardInfo
	SubscriptionInfo
	ShardOwner
	ContinuousQueryInfo
	UserInfo
	UserPrivilege
	Command
	CreateNodeCommand
	DeleteNodeCommand
	CreateDatabaseCommand
	DropDatabaseCommand
	CreateRetentionPolicyCommand
	DropRetentionPolicyCommand
	SetDefaultRetentionPolicyCommand
	UpdateRetentionPolicyCommand
	CreateShardGroupCommand
	DeleteShardGroupCommand
	CreateContinuousQueryCommand
	DropContinuousQueryCommand
	CreateUserCommand
	DropUserCommand
	UpdateUserCommand
	SetPrivilegeCommand
	SetDataCommand
	SetAdminPrivilegeCommand
	UpdateNodeCommand
	CreateSubscriptionCommand
	DropSubscriptionCommand
	RemovePeerCommand
	CreateMetaNodeCommand
	CreateDataNodeCommand
	UpdateDataNodeCommand
	DeleteMetaNodeCommand
	DeleteDataNodeCommand
	Response
	SetMetaNodeCommand
	DropShardCommand
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Command_Type int32

const (
	Command_CreateNodeCommand                Command_Type = 1
	Command_DeleteNodeCommand                Command_Type = 2
	Command_CreateDatabaseCommand            Command_Type = 3
	Command_DropDatabaseCommand              Command_Type = 4
	Command_CreateRetentionPolicyCommand     Command_Type = 5
	Command_DropRetentionPolicyCommand       Command_Type = 6
	Command_SetDefaultRetentionPolicyCommand Command_Type = 7
	Command_UpdateRetentionPolicyCommand     Command_Type = 8
	Command_CreateShardGroupCommand          Command_Type = 9
	Command_DeleteShardGroupCommand          Command_Type = 10
	Command_CreateContinuousQueryCommand     Command_Type = 11
	Command_DropContinuousQueryCommand       Command_Type = 12
	Command_CreateUserCommand                Command_Type = 13
	Command_DropUserCommand                  Command_Type = 14
	Command_UpdateUserCommand                Command_Type = 15
	Command_SetPrivilegeCommand              Command_Type = 16
	Command_SetDataCommand                   Command_Type = 17
	Command_SetAdminPrivilegeCommand         Command_Type = 18
	Command_UpdateNodeCommand                Command_Type = 19
	Command_CreateSubscriptionCommand        Command_Type = 21
	Command_DropSubscriptionCommand          Command_Type = 22
	Command_RemovePeerCommand                Command_Type = 23
	Command_CreateMetaNodeCommand            Command_Type = 24
	Command_CreateDataNodeCommand            Command_Type = 25
	Command_UpdateDataNodeCommand            Command_Type = 26
	Command_DeleteMetaNodeCommand            Command_Type = 27
	Command_DeleteDataNodeCommand            Command_Type = 28
	Command_SetMetaNodeCommand               Command_Type = 29
	Command_DropShardCommand                 Command_Type = 30
)

var Command_Type_name = map[int32]string{
	1:  "CreateNodeCommand",
	2:  "DeleteNodeCommand",
	3:  "CreateDatabaseCommand",
	4:  "DropDatabaseCommand",
	5:  "CreateRetentionPolicyCommand",
	6:  "DropRetentionPolicyCommand",
	7:  "SetDefaultRetentionPolicyCommand",
	8:  "UpdateRetentionPolicyCommand",
	9:  "CreateShardGroupCommand",
	10: "DeleteShardGroupCommand",
	11: "CreateContinuousQueryCommand",
	12: "DropContinuousQueryCommand",
	13: "CreateUserCommand",
	14: "DropUserCommand",
	15: "UpdateUserCommand",
	16: "SetPrivilegeCommand",
	17: "SetDataCommand",
	18: "SetAdminPrivilegeCommand",
	19: "UpdateNodeCommand",
	21: "CreateSubscriptionCommand",
	22: "DropSubscriptionCommand",
	23: "RemovePeerCommand",
	24: "CreateMetaNodeCommand",
	25: "CreateDataNodeCommand",
	26: "UpdateDataNodeCommand",
	27: "DeleteMetaNodeCommand",
	28: "DeleteDataNodeCommand",
	29: "SetMetaNodeCommand",
	30: "DropShardCommand",
}
var Command_Type_value = map[string]int32{
	"CreateNodeCommand":                1,
	"DeleteNodeCommand":                2,
	"CreateDatabaseCommand":            3,
	"DropDatabaseCommand":              4,
	"CreateRetentionPolicyCommand":     5,
	"DropRetentionPolicyCommand":       6,
	"SetDefaultRetentionPolicyCommand": 7,
	"UpdateRetentionPolicyCommand":     8,
	"CreateShardGroupCommand":          9,
	"DeleteShardGroupCommand":          10,
	"CreateContinuousQueryCommand":     11,
	"DropContinuousQueryCommand":       12,
	"CreateUserCommand":                13,
	"DropUserCommand":                  14,
	"UpdateUserCommand":                15,
	"SetPrivilegeCommand":              16,
	"SetDataCommand":                   17,
	"SetAdminPrivilegeCommand":         18,
	"UpdateNodeCommand":                19,
	"CreateSubscriptionCommand":        21,
	"DropSubscriptionCommand":          22,
	"RemovePeerCommand":                23,
	"CreateMetaNodeCommand":            24,
	"CreateDataNodeCommand":            25,
	"UpdateDataNodeCommand":            26,
	"DeleteMetaNodeCommand":            27,
	"DeleteDataNodeCommand":            28,
	"SetMetaNodeCommand":               29,
	"DropShardCommand":                 30,
}

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}
func (x Command_Type) String() string {
	return proto.EnumName(Command_Type_name, int32(x))
}
func (x *Command_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Command_Type_value, data, "Command_Type")
	if err != nil {
		return err
	}
	*x = Command_Type(value)
	return nil
}
func (Command_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptorMeta, []int{12, 0} }

type Data struct {
	Term            *uint64         `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	Index           *uint64         `protobuf:"varint,2,req,name=Index" json:"Index,omitempty"`
	ClusterID       *uint64         `protobuf:"varint,3,req,name=ClusterID" json:"ClusterID,omitempty"`
	Nodes           []*NodeInfo     `protobuf:"bytes,4,rep,name=Nodes" json:"Nodes,omitempty"`
	Databases       []*DatabaseInfo `protobuf:"bytes,5,rep,name=Databases" json:"Databases,omitempty"`
	Users           []*UserInfo     `protobuf:"bytes,6,rep,name=Users" json:"Users,omitempty"`
	MaxNodeID       *uint64         `protobuf:"varint,7,req,name=MaxNodeID" json:"MaxNodeID,omitempty"`
	MaxShardGroupID *uint64         `protobuf:"varint,8,req,name=MaxShardGroupID" json:"MaxShardGroupID,omitempty"`
	MaxShardID      *uint64         `protobuf:"varint,9,req,name=MaxShardID" json:"MaxShardID,omitempty"`
	// added for 0.10.0
	DataNodes        []*NodeInfo `protobuf:"bytes,10,rep,name=DataNodes" json:"DataNodes,omitempty"`
	MetaNodes        []*NodeInfo `protobuf:"bytes,11,rep,name=MetaNodes" json:"MetaNodes,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{0} }

func (m *Data) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *Data) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *Data) GetClusterID() uint64 {
	if m != nil && m.ClusterID != nil {
		return *m.ClusterID
	}
	return 0
}

func (m *Data) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Data) GetDatabases() []*DatabaseInfo {
	if m != nil {
		return m.Databases
	}
	return nil
}

func (m *Data) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Data) GetMaxNodeID() uint64 {
	if m != nil && m.MaxNodeID != nil {
		return *m.MaxNodeID
	}
	return 0
}

func (m *Data) GetMaxShardGroupID() uint64 {
	if m != nil && m.MaxShardGroupID != nil {
		return *m.MaxShardGroupID
	}
	return 0
}

func (m *Data) GetMaxShardID() uint64 {
	if m != nil && m.MaxShardID != nil {
		return *m.MaxShardID
	}
	return 0
}

func (m *Data) GetDataNodes() []*NodeInfo {
	if m != nil {
		return m.DataNodes
	}
	return nil
}

func (m *Data) GetMetaNodes() []*NodeInfo {
	if m != nil {
		return m.MetaNodes
	}
	return nil
}

type NodeInfo struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Host             *string `protobuf:"bytes,2,req,name=Host" json:"Host,omitempty"`
	TCPHost          *string `protobuf:"bytes,3,opt,name=TCPHost" json:"TCPHost,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{1} }

func (m *NodeInfo) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *NodeInfo) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *NodeInfo) GetTCPHost() string {
	if m != nil && m.TCPHost != nil {
		return *m.TCPHost
	}
	return ""
}

type DatabaseInfo struct {
	Name                   *string                `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	DefaultRetentionPolicy *string                `protobuf:"bytes,2,req,name=DefaultRetentionPolicy" json:"DefaultRetentionPolicy,omitempty"`
	RetentionPolicies      []*RetentionPolicyInfo `protobuf:"bytes,3,rep,name=RetentionPolicies" json:"RetentionPolicies,omitempty"`
	ContinuousQueries      []*ContinuousQueryInfo `protobuf:"bytes,4,rep,name=ContinuousQueries" json:"ContinuousQueries,omitempty"`
	XXX_unrecognized       []byte                 `json:"-"`
}

func (m *DatabaseInfo) Reset()                    { *m = DatabaseInfo{} }
func (m *DatabaseInfo) String() string            { return proto.CompactTextString(m) }
func (*DatabaseInfo) ProtoMessage()               {}
func (*DatabaseInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{2} }

func (m *DatabaseInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DatabaseInfo) GetDefaultRetentionPolicy() string {
	if m != nil && m.DefaultRetentionPolicy != nil {
		return *m.DefaultRetentionPolicy
	}
	return ""
}

func (m *DatabaseInfo) GetRetentionPolicies() []*RetentionPolicyInfo {
	if m != nil {
		return m.RetentionPolicies
	}
	return nil
}

func (m *DatabaseInfo) GetContinuousQueries() []*ContinuousQueryInfo {
	if m != nil {
		return m.ContinuousQueries
	}
	return nil
}

type RetentionPolicySpec struct {
	Name               *string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Duration           *int64  `protobuf:"varint,2,opt,name=Duration" json:"Duration,omitempty"`
	ShardGroupDuration *int64  `protobuf:"varint,3,opt,name=ShardGroupDuration" json:"ShardGroupDuration,omitempty"`
	ReplicaN           *uint32 `protobuf:"varint,4,opt,name=ReplicaN" json:"ReplicaN,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *RetentionPolicySpec) Reset()                    { *m = RetentionPolicySpec{} }
func (m *RetentionPolicySpec) String() string            { return proto.CompactTextString(m) }
func (*RetentionPolicySpec) ProtoMessage()               {}
func (*RetentionPolicySpec) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{3} }

func (m *RetentionPolicySpec) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RetentionPolicySpec) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *RetentionPolicySpec) GetShardGroupDuration() int64 {
	if m != nil && m.ShardGroupDuration != nil {
		return *m.ShardGroupDuration
	}
	return 0
}

func (m *RetentionPolicySpec) GetReplicaN() uint32 {
	if m != nil && m.ReplicaN != nil {
		return *m.ReplicaN
	}
	return 0
}

type RetentionPolicyInfo struct {
	Name               *string             `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Duration           *int64              `protobuf:"varint,2,req,name=Duration" json:"Duration,omitempty"`
	ShardGroupDuration *int64              `protobuf:"varint,3,req,name=ShardGroupDuration" json:"ShardGroupDuration,omitempty"`
	ReplicaN           *uint32             `protobuf:"varint,4,req,name=ReplicaN" json:"ReplicaN,omitempty"`
	ShardGroups        []*ShardGroupInfo   `protobuf:"bytes,5,rep,name=ShardGroups" json:"ShardGroups,omitempty"`
	Subscriptions      []*SubscriptionInfo `protobuf:"bytes,6,rep,name=Subscriptions" json:"Subscriptions,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *RetentionPolicyInfo) Reset()                    { *m = RetentionPolicyInfo{} }
func (m *RetentionPolicyInfo) String() string            { return proto.CompactTextString(m) }
func (*RetentionPolicyInfo) ProtoMessage()               {}
func (*RetentionPolicyInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{4} }

func (m *RetentionPolicyInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RetentionPolicyInfo) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *RetentionPolicyInfo) GetShardGroupDuration() int64 {
	if m != nil && m.ShardGroupDuration != nil {
		return *m.ShardGroupDuration
	}
	return 0
}

func (m *RetentionPolicyInfo) GetReplicaN() uint32 {
	if m != nil && m.ReplicaN != nil {
		return *m.ReplicaN
	}
	return 0
}

func (m *RetentionPolicyInfo) GetShardGroups() []*ShardGroupInfo {
	if m != nil {
		return m.ShardGroups
	}
	return nil
}

func (m *RetentionPolicyInfo) GetSubscriptions() []*SubscriptionInfo {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type ShardGroupInfo struct {
	ID               *uint64      `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	StartTime        *int64       `protobuf:"varint,2,req,name=StartTime" json:"StartTime,omitempty"`
	EndTime          *int64       `protobuf:"varint,3,req,name=EndTime" json:"EndTime,omitempty"`
	DeletedAt        *int64       `protobuf:"varint,4,req,name=DeletedAt" json:"DeletedAt,omitempty"`
	Shards           []*ShardInfo `protobuf:"bytes,5,rep,name=Shards" json:"Shards,omitempty"`
	TruncatedAt      *int64       `protobuf:"varint,6,opt,name=TruncatedAt" json:"TruncatedAt,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ShardGroupInfo) Reset()                    { *m = ShardGroupInfo{} }
func (m *ShardGroupInfo) String() string            { return proto.CompactTextString(m) }
func (*ShardGroupInfo) ProtoMessage()               {}
func (*ShardGroupInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{5} }

func (m *ShardGroupInfo) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *ShardGroupInfo) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *ShardGroupInfo) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *ShardGroupInfo) GetDeletedAt() int64 {
	if m != nil && m.DeletedAt != nil {
		return *m.DeletedAt
	}
	return 0
}

func (m *ShardGroupInfo) GetShards() []*ShardInfo {
	if m != nil {
		return m.Shards
	}
	return nil
}

func (m *ShardGroupInfo) GetTruncatedAt() int64 {
	if m != nil && m.TruncatedAt != nil {
		return *m.TruncatedAt
	}
	return 0
}

type ShardInfo struct {
	ID               *uint64       `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	OwnerIDs         []uint64      `protobuf:"varint,2,rep,name=OwnerIDs" json:"OwnerIDs,omitempty"`
	Owners           []*ShardOwner `protobuf:"bytes,3,rep,name=Owners" json:"Owners,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ShardInfo) Reset()                    { *m = ShardInfo{} }
func (m *ShardInfo) String() string            { return proto.CompactTextString(m) }
func (*ShardInfo) ProtoMessage()               {}
func (*ShardInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{6} }

func (m *ShardInfo) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *ShardInfo) GetOwnerIDs() []uint64 {
	if m != nil {
		return m.OwnerIDs
	}
	return nil
}

func (m *ShardInfo) GetOwners() []*ShardOwner {
	if m != nil {
		return m.Owners
	}
	return nil
}

type SubscriptionInfo struct {
	Name             *string  `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Mode             *string  `protobuf:"bytes,2,req,name=Mode" json:"Mode,omitempty"`
	Destinations     []string `protobuf:"bytes,3,rep,name=Destinations" json:"Destinations,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SubscriptionInfo) Reset()                    { *m = SubscriptionInfo{} }
func (m *SubscriptionInfo) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionInfo) ProtoMessage()               {}
func (*SubscriptionInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{7} }

func (m *SubscriptionInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SubscriptionInfo) GetMode() string {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return ""
}

func (m *SubscriptionInfo) GetDestinations() []string {
	if m != nil {
		return m.Destinations
	}
	return nil
}

type ShardOwner struct {
	NodeID           *uint64 `protobuf:"varint,1,req,name=NodeID" json:"NodeID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShardOwner) Reset()                    { *m = ShardOwner{} }
func (m *ShardOwner) String() string            { return proto.CompactTextString(m) }
func (*ShardOwner) ProtoMessage()               {}
func (*ShardOwner) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{8} }

func (m *ShardOwner) GetNodeID() uint64 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

type ContinuousQueryInfo struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Query            *string `protobuf:"bytes,2,req,name=Query" json:"Query,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContinuousQueryInfo) Reset()                    { *m = ContinuousQueryInfo{} }
func (m *ContinuousQueryInfo) String() string            { return proto.CompactTextString(m) }
func (*ContinuousQueryInfo) ProtoMessage()               {}
func (*ContinuousQueryInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{9} }

func (m *ContinuousQueryInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ContinuousQueryInfo) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

type UserInfo struct {
	Name             *string          `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Hash             *string          `protobuf:"bytes,2,req,name=Hash" json:"Hash,omitempty"`
	Admin            *bool            `protobuf:"varint,3,req,name=Admin" json:"Admin,omitempty"`
	Privileges       []*UserPrivilege `protobuf:"bytes,4,rep,name=Privileges" json:"Privileges,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{10} }

func (m *UserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserInfo) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *UserInfo) GetAdmin() bool {
	if m != nil && m.Admin != nil {
		return *m.Admin
	}
	return false
}

func (m *UserInfo) GetPrivileges() []*UserPrivilege {
	if m != nil {
		return m.Privileges
	}
	return nil
}

type UserPrivilege struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Privilege        *int32  `protobuf:"varint,2,req,name=Privilege" json:"Privilege,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserPrivilege) Reset()                    { *m = UserPrivilege{} }
func (m *UserPrivilege) String() string            { return proto.CompactTextString(m) }
func (*UserPrivilege) ProtoMessage()               {}
func (*UserPrivilege) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{11} }

func (m *UserPrivilege) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *UserPrivilege) GetPrivilege() int32 {
	if m != nil && m.Privilege != nil {
		return *m.Privilege
	}
	return 0
}

type Command struct {
	Type                         *Command_Type `protobuf:"varint,1,req,name=type,enum=internal.Command_Type" json:"type,omitempty"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{12} }

var extRange_Command = []proto.ExtensionRange{
	{Start: 100, End: 536870911},
}

func (*Command) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Command
}

func (m *Command) GetType() Command_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Command_CreateNodeCommand
}

// This isn't used in >= 0.10.0. Kept around for upgrade purposes. Instead
// look at CreateDataNodeCommand and CreateMetaNodeCommand
type CreateNodeCommand struct {
	Host             *string `protobuf:"bytes,1,req,name=Host" json:"Host,omitempty"`
	Rand             *uint64 `protobuf:"varint,2,req,name=Rand" json:"Rand,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateNodeCommand) Reset()                    { *m = CreateNodeCommand{} }
func (m *CreateNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeCommand) ProtoMessage()               {}
func (*CreateNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{13} }

func (m *CreateNodeCommand) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *CreateNodeCommand) GetRand() uint64 {
	if m != nil && m.Rand != nil {
		return *m.Rand
	}
	return 0
}

var E_CreateNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateNodeCommand)(nil),
	Field:         101,
	Name:          "internal.CreateNodeCommand.command",
	Tag:           "bytes,101,opt,name=command",
	Filename:      "meta.proto",
}

type DeleteNodeCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Force            *bool   `protobuf:"varint,2,req,name=Force" json:"Force,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteNodeCommand) Reset()                    { *m = DeleteNodeCommand{} }
func (m *DeleteNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeCommand) ProtoMessage()               {}
func (*DeleteNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{14} }

func (m *DeleteNodeCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *DeleteNodeCommand) GetForce() bool {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return false
}

var E_DeleteNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DeleteNodeCommand)(nil),
	Field:         102,
	Name:          "internal.DeleteNodeCommand.command",
	Tag:           "bytes,102,opt,name=command",
	Filename:      "meta.proto",
}

type CreateDatabaseCommand struct {
	Name             *string              `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	RetentionPolicy  *RetentionPolicyInfo `protobuf:"bytes,2,opt,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CreateDatabaseCommand) Reset()                    { *m = CreateDatabaseCommand{} }
func (m *CreateDatabaseCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateDatabaseCommand) ProtoMessage()               {}
func (*CreateDatabaseCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{15} }

func (m *CreateDatabaseCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateDatabaseCommand) GetRetentionPolicy() *RetentionPolicyInfo {
	if m != nil {
		return m.RetentionPolicy
	}
	return nil
}

var E_CreateDatabaseCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateDatabaseCommand)(nil),
	Field:         103,
	Name:          "internal.CreateDatabaseCommand.command",
	Tag:           "bytes,103,opt,name=command",
	Filename:      "meta.proto",
}

type DropDatabaseCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropDatabaseCommand) Reset()                    { *m = DropDatabaseCommand{} }
func (m *DropDatabaseCommand) String() string            { return proto.CompactTextString(m) }
func (*DropDatabaseCommand) ProtoMessage()               {}
func (*DropDatabaseCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{16} }

func (m *DropDatabaseCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_DropDatabaseCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropDatabaseCommand)(nil),
	Field:         104,
	Name:          "internal.DropDatabaseCommand.command",
	Tag:           "bytes,104,opt,name=command",
	Filename:      "meta.proto",
}

type CreateRetentionPolicyCommand struct {
	Database         *string              `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy  *RetentionPolicyInfo `protobuf:"bytes,2,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	MakeDefault      *bool                `protobuf:"varint,3,req,name=MakeDefault" json:"MakeDefault,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CreateRetentionPolicyCommand) Reset()         { *m = CreateRetentionPolicyCommand{} }
func (m *CreateRetentionPolicyCommand) String() string { return proto.CompactTextString(m) }
func (*CreateRetentionPolicyCommand) ProtoMessage()    {}
func (*CreateRetentionPolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{17}
}

func (m *CreateRetentionPolicyCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateRetentionPolicyCommand) GetRetentionPolicy() *RetentionPolicyInfo {
	if m != nil {
		return m.RetentionPolicy
	}
	return nil
}

func (m *CreateRetentionPolicyCommand) GetMakeDefault() bool {
	if m != nil && m.MakeDefault != nil {
		return *m.MakeDefault
	}
	return false
}

var E_CreateRetentionPolicyCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateRetentionPolicyCommand)(nil),
	Field:         105,
	Name:          "internal.CreateRetentionPolicyCommand.command",
	Tag:           "bytes,105,opt,name=command",
	Filename:      "meta.proto",
}

type DropRetentionPolicyCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropRetentionPolicyCommand) Reset()                    { *m = DropRetentionPolicyCommand{} }
func (m *DropRetentionPolicyCommand) String() string            { return proto.CompactTextString(m) }
func (*DropRetentionPolicyCommand) ProtoMessage()               {}
func (*DropRetentionPolicyCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{18} }

func (m *DropRetentionPolicyCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *DropRetentionPolicyCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_DropRetentionPolicyCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropRetentionPolicyCommand)(nil),
	Field:         106,
	Name:          "internal.DropRetentionPolicyCommand.command",
	Tag:           "bytes,106,opt,name=command",
	Filename:      "meta.proto",
}

type SetDefaultRetentionPolicyCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetDefaultRetentionPolicyCommand) Reset()         { *m = SetDefaultRetentionPolicyCommand{} }
func (m *SetDefaultRetentionPolicyCommand) String() string { return proto.CompactTextString(m) }
func (*SetDefaultRetentionPolicyCommand) ProtoMessage()    {}
func (*SetDefaultRetentionPolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{19}
}

func (m *SetDefaultRetentionPolicyCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *SetDefaultRetentionPolicyCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_SetDefaultRetentionPolicyCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetDefaultRetentionPolicyCommand)(nil),
	Field:         107,
	Name:          "internal.SetDefaultRetentionPolicyCommand.command",
	Tag:           "bytes,107,opt,name=command",
	Filename:      "meta.proto",
}

type UpdateRetentionPolicyCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	NewName          *string `protobuf:"bytes,3,opt,name=NewName" json:"NewName,omitempty"`
	Duration         *int64  `protobuf:"varint,4,opt,name=Duration" json:"Duration,omitempty"`
	ReplicaN         *uint32 `protobuf:"varint,5,opt,name=ReplicaN" json:"ReplicaN,omitempty"`
	MakeDefault      *bool   `protobuf:"varint,6,opt,name=MakeDefault" json:"MakeDefault,omitempty"`
	ShardDuration    *int64  `protobuf:"varint,7,opt,name=ShardDuration" json:"ShardDuration,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateRetentionPolicyCommand) Reset()         { *m = UpdateRetentionPolicyCommand{} }
func (m *UpdateRetentionPolicyCommand) String() string { return proto.CompactTextString(m) }
func (*UpdateRetentionPolicyCommand) ProtoMessage()    {}
func (*UpdateRetentionPolicyCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{20}
}

func (m *UpdateRetentionPolicyCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *UpdateRetentionPolicyCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UpdateRetentionPolicyCommand) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

func (m *UpdateRetentionPolicyCommand) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *UpdateRetentionPolicyCommand) GetReplicaN() uint32 {
	if m != nil && m.ReplicaN != nil {
		return *m.ReplicaN
	}
	return 0
}

func (m *UpdateRetentionPolicyCommand) GetMakeDefault() bool {
	if m != nil && m.MakeDefault != nil {
		return *m.MakeDefault
	}
	return false
}

func (m *UpdateRetentionPolicyCommand) GetShardDuration() int64 {
	if m != nil && m.ShardDuration != nil {
		return *m.ShardDuration
	}
	return 0
}

var E_UpdateRetentionPolicyCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*UpdateRetentionPolicyCommand)(nil),
	Field:         108,
	Name:          "internal.UpdateRetentionPolicyCommand.command",
	Tag:           "bytes,108,opt,name=command",
	Filename:      "meta.proto",
}

type CreateShardGroupCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Policy           *string `protobuf:"bytes,2,req,name=Policy" json:"Policy,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=Timestamp" json:"Timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateShardGroupCommand) Reset()                    { *m = CreateShardGroupCommand{} }
func (m *CreateShardGroupCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateShardGroupCommand) ProtoMessage()               {}
func (*CreateShardGroupCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{21} }

func (m *CreateShardGroupCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateShardGroupCommand) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *CreateShardGroupCommand) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

var E_CreateShardGroupCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateShardGroupCommand)(nil),
	Field:         109,
	Name:          "internal.CreateShardGroupCommand.command",
	Tag:           "bytes,109,opt,name=command",
	Filename:      "meta.proto",
}

type DeleteShardGroupCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Policy           *string `protobuf:"bytes,2,req,name=Policy" json:"Policy,omitempty"`
	ShardGroupID     *uint64 `protobuf:"varint,3,req,name=ShardGroupID" json:"ShardGroupID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteShardGroupCommand) Reset()                    { *m = DeleteShardGroupCommand{} }
func (m *DeleteShardGroupCommand) String() string            { return proto.CompactTextString(m) }
func (*DeleteShardGroupCommand) ProtoMessage()               {}
func (*DeleteShardGroupCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{22} }

func (m *DeleteShardGroupCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *DeleteShardGroupCommand) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *DeleteShardGroupCommand) GetShardGroupID() uint64 {
	if m != nil && m.ShardGroupID != nil {
		return *m.ShardGroupID
	}
	return 0
}

var E_DeleteShardGroupCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DeleteShardGroupCommand)(nil),
	Field:         110,
	Name:          "internal.DeleteShardGroupCommand.command",
	Tag:           "bytes,110,opt,name=command",
	Filename:      "meta.proto",
}

type CreateContinuousQueryCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	Query            *string `protobuf:"bytes,3,req,name=Query" json:"Query,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateContinuousQueryCommand) Reset()         { *m = CreateContinuousQueryCommand{} }
func (m *CreateContinuousQueryCommand) String() string { return proto.CompactTextString(m) }
func (*CreateContinuousQueryCommand) ProtoMessage()    {}
func (*CreateContinuousQueryCommand) Descriptor() ([]byte, []int) {
	return fileDescriptorMeta, []int{23}
}

func (m *CreateContinuousQueryCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateContinuousQueryCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateContinuousQueryCommand) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

var E_CreateContinuousQueryCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateContinuousQueryCommand)(nil),
	Field:         111,
	Name:          "internal.CreateContinuousQueryCommand.command",
	Tag:           "bytes,111,opt,name=command",
	Filename:      "meta.proto",
}

type DropContinuousQueryCommand struct {
	Database         *string `protobuf:"bytes,1,req,name=Database" json:"Database,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropContinuousQueryCommand) Reset()                    { *m = DropContinuousQueryCommand{} }
func (m *DropContinuousQueryCommand) String() string            { return proto.CompactTextString(m) }
func (*DropContinuousQueryCommand) ProtoMessage()               {}
func (*DropContinuousQueryCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{24} }

func (m *DropContinuousQueryCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *DropContinuousQueryCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_DropContinuousQueryCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropContinuousQueryCommand)(nil),
	Field:         112,
	Name:          "internal.DropContinuousQueryCommand.command",
	Tag:           "bytes,112,opt,name=command",
	Filename:      "meta.proto",
}

type CreateUserCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Hash             *string `protobuf:"bytes,2,req,name=Hash" json:"Hash,omitempty"`
	Admin            *bool   `protobuf:"varint,3,req,name=Admin" json:"Admin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateUserCommand) Reset()                    { *m = CreateUserCommand{} }
func (m *CreateUserCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateUserCommand) ProtoMessage()               {}
func (*CreateUserCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{25} }

func (m *CreateUserCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateUserCommand) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *CreateUserCommand) GetAdmin() bool {
	if m != nil && m.Admin != nil {
		return *m.Admin
	}
	return false
}

var E_CreateUserCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateUserCommand)(nil),
	Field:         113,
	Name:          "internal.CreateUserCommand.command",
	Tag:           "bytes,113,opt,name=command",
	Filename:      "meta.proto",
}

type DropUserCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropUserCommand) Reset()                    { *m = DropUserCommand{} }
func (m *DropUserCommand) String() string            { return proto.CompactTextString(m) }
func (*DropUserCommand) ProtoMessage()               {}
func (*DropUserCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{26} }

func (m *DropUserCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

var E_DropUserCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropUserCommand)(nil),
	Field:         114,
	Name:          "internal.DropUserCommand.command",
	Tag:           "bytes,114,opt,name=command",
	Filename:      "meta.proto",
}

type UpdateUserCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Hash             *string `protobuf:"bytes,2,req,name=Hash" json:"Hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateUserCommand) Reset()                    { *m = UpdateUserCommand{} }
func (m *UpdateUserCommand) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserCommand) ProtoMessage()               {}
func (*UpdateUserCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{27} }

func (m *UpdateUserCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UpdateUserCommand) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

var E_UpdateUserCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*UpdateUserCommand)(nil),
	Field:         115,
	Name:          "internal.UpdateUserCommand.command",
	Tag:           "bytes,115,opt,name=command",
	Filename:      "meta.proto",
}

type SetPrivilegeCommand struct {
	Username         *string `protobuf:"bytes,1,req,name=Username" json:"Username,omitempty"`
	Database         *string `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	Privilege        *int32  `protobuf:"varint,3,req,name=Privilege" json:"Privilege,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetPrivilegeCommand) Reset()                    { *m = SetPrivilegeCommand{} }
func (m *SetPrivilegeCommand) String() string            { return proto.CompactTextString(m) }
func (*SetPrivilegeCommand) ProtoMessage()               {}
func (*SetPrivilegeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{28} }

func (m *SetPrivilegeCommand) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *SetPrivilegeCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *SetPrivilegeCommand) GetPrivilege() int32 {
	if m != nil && m.Privilege != nil {
		return *m.Privilege
	}
	return 0
}

var E_SetPrivilegeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetPrivilegeCommand)(nil),
	Field:         116,
	Name:          "internal.SetPrivilegeCommand.command",
	Tag:           "bytes,116,opt,name=command",
	Filename:      "meta.proto",
}

type SetDataCommand struct {
	Data             *Data  `protobuf:"bytes,1,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetDataCommand) Reset()                    { *m = SetDataCommand{} }
func (m *SetDataCommand) String() string            { return proto.CompactTextString(m) }
func (*SetDataCommand) ProtoMessage()               {}
func (*SetDataCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{29} }

func (m *SetDataCommand) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

var E_SetDataCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetDataCommand)(nil),
	Field:         117,
	Name:          "internal.SetDataCommand.command",
	Tag:           "bytes,117,opt,name=command",
	Filename:      "meta.proto",
}

type SetAdminPrivilegeCommand struct {
	Username         *string `protobuf:"bytes,1,req,name=Username" json:"Username,omitempty"`
	Admin            *bool   `protobuf:"varint,2,req,name=Admin" json:"Admin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetAdminPrivilegeCommand) Reset()                    { *m = SetAdminPrivilegeCommand{} }
func (m *SetAdminPrivilegeCommand) String() string            { return proto.CompactTextString(m) }
func (*SetAdminPrivilegeCommand) ProtoMessage()               {}
func (*SetAdminPrivilegeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{30} }

func (m *SetAdminPrivilegeCommand) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *SetAdminPrivilegeCommand) GetAdmin() bool {
	if m != nil && m.Admin != nil {
		return *m.Admin
	}
	return false
}

var E_SetAdminPrivilegeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetAdminPrivilegeCommand)(nil),
	Field:         118,
	Name:          "internal.SetAdminPrivilegeCommand.command",
	Tag:           "bytes,118,opt,name=command",
	Filename:      "meta.proto",
}

type UpdateNodeCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Host             *string `protobuf:"bytes,2,req,name=Host" json:"Host,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateNodeCommand) Reset()                    { *m = UpdateNodeCommand{} }
func (m *UpdateNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeCommand) ProtoMessage()               {}
func (*UpdateNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{31} }

func (m *UpdateNodeCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *UpdateNodeCommand) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

var E_UpdateNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*UpdateNodeCommand)(nil),
	Field:         119,
	Name:          "internal.UpdateNodeCommand.command",
	Tag:           "bytes,119,opt,name=command",
	Filename:      "meta.proto",
}

type CreateSubscriptionCommand struct {
	Name             *string  `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Database         *string  `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy  *string  `protobuf:"bytes,3,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	Mode             *string  `protobuf:"bytes,4,req,name=Mode" json:"Mode,omitempty"`
	Destinations     []string `protobuf:"bytes,5,rep,name=Destinations" json:"Destinations,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CreateSubscriptionCommand) Reset()                    { *m = CreateSubscriptionCommand{} }
func (m *CreateSubscriptionCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateSubscriptionCommand) ProtoMessage()               {}
func (*CreateSubscriptionCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{32} }

func (m *CreateSubscriptionCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateSubscriptionCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *CreateSubscriptionCommand) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

func (m *CreateSubscriptionCommand) GetMode() string {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return ""
}

func (m *CreateSubscriptionCommand) GetDestinations() []string {
	if m != nil {
		return m.Destinations
	}
	return nil
}

var E_CreateSubscriptionCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateSubscriptionCommand)(nil),
	Field:         121,
	Name:          "internal.CreateSubscriptionCommand.command",
	Tag:           "bytes,121,opt,name=command",
	Filename:      "meta.proto",
}

type DropSubscriptionCommand struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Database         *string `protobuf:"bytes,2,req,name=Database" json:"Database,omitempty"`
	RetentionPolicy  *string `protobuf:"bytes,3,req,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropSubscriptionCommand) Reset()                    { *m = DropSubscriptionCommand{} }
func (m *DropSubscriptionCommand) String() string            { return proto.CompactTextString(m) }
func (*DropSubscriptionCommand) ProtoMessage()               {}
func (*DropSubscriptionCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{33} }

func (m *DropSubscriptionCommand) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DropSubscriptionCommand) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *DropSubscriptionCommand) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

var E_DropSubscriptionCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropSubscriptionCommand)(nil),
	Field:         122,
	Name:          "internal.DropSubscriptionCommand.command",
	Tag:           "bytes,122,opt,name=command",
	Filename:      "meta.proto",
}

type RemovePeerCommand struct {
	ID               *uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Addr             *string `protobuf:"bytes,2,req,name=Addr" json:"Addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RemovePeerCommand) Reset()                    { *m = RemovePeerCommand{} }
func (m *RemovePeerCommand) String() string            { return proto.CompactTextString(m) }
func (*RemovePeerCommand) ProtoMessage()               {}
func (*RemovePeerCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{34} }

func (m *RemovePeerCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *RemovePeerCommand) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

var E_RemovePeerCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*RemovePeerCommand)(nil),
	Field:         123,
	Name:          "internal.RemovePeerCommand.command",
	Tag:           "bytes,123,opt,name=command",
	Filename:      "meta.proto",
}

type CreateMetaNodeCommand struct {
	HTTPAddr         *string `protobuf:"bytes,1,req,name=HTTPAddr" json:"HTTPAddr,omitempty"`
	TCPAddr          *string `protobuf:"bytes,2,req,name=TCPAddr" json:"TCPAddr,omitempty"`
	Rand             *uint64 `protobuf:"varint,3,req,name=Rand" json:"Rand,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateMetaNodeCommand) Reset()                    { *m = CreateMetaNodeCommand{} }
func (m *CreateMetaNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateMetaNodeCommand) ProtoMessage()               {}
func (*CreateMetaNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{35} }

func (m *CreateMetaNodeCommand) GetHTTPAddr() string {
	if m != nil && m.HTTPAddr != nil {
		return *m.HTTPAddr
	}
	return ""
}

func (m *CreateMetaNodeCommand) GetTCPAddr() string {
	if m != nil && m.TCPAddr != nil {
		return *m.TCPAddr
	}
	return ""
}

func (m *CreateMetaNodeCommand) GetRand() uint64 {
	if m != nil && m.Rand != nil {
		return *m.Rand
	}
	return 0
}

var E_CreateMetaNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateMetaNodeCommand)(nil),
	Field:         124,
	Name:          "internal.CreateMetaNodeCommand.command",
	Tag:           "bytes,124,opt,name=command",
	Filename:      "meta.proto",
}

type CreateDataNodeCommand struct {
	HTTPAddr         *string `protobuf:"bytes,1,req,name=HTTPAddr" json:"HTTPAddr,omitempty"`
	TCPAddr          *string `protobuf:"bytes,2,req,name=TCPAddr" json:"TCPAddr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateDataNodeCommand) Reset()                    { *m = CreateDataNodeCommand{} }
func (m *CreateDataNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*CreateDataNodeCommand) ProtoMessage()               {}
func (*CreateDataNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{36} }

func (m *CreateDataNodeCommand) GetHTTPAddr() string {
	if m != nil && m.HTTPAddr != nil {
		return *m.HTTPAddr
	}
	return ""
}

func (m *CreateDataNodeCommand) GetTCPAddr() string {
	if m != nil && m.TCPAddr != nil {
		return *m.TCPAddr
	}
	return ""
}

var E_CreateDataNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*CreateDataNodeCommand)(nil),
	Field:         125,
	Name:          "internal.CreateDataNodeCommand.command",
	Tag:           "bytes,125,opt,name=command",
	Filename:      "meta.proto",
}

type UpdateDataNodeCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Host             *string `protobuf:"bytes,2,req,name=Host" json:"Host,omitempty"`
	TCPHost          *string `protobuf:"bytes,3,req,name=TCPHost" json:"TCPHost,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateDataNodeCommand) Reset()                    { *m = UpdateDataNodeCommand{} }
func (m *UpdateDataNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*UpdateDataNodeCommand) ProtoMessage()               {}
func (*UpdateDataNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{37} }

func (m *UpdateDataNodeCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *UpdateDataNodeCommand) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *UpdateDataNodeCommand) GetTCPHost() string {
	if m != nil && m.TCPHost != nil {
		return *m.TCPHost
	}
	return ""
}

var E_UpdateDataNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*UpdateDataNodeCommand)(nil),
	Field:         126,
	Name:          "internal.UpdateDataNodeCommand.command",
	Tag:           "bytes,126,opt,name=command",
	Filename:      "meta.proto",
}

type DeleteMetaNodeCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteMetaNodeCommand) Reset()                    { *m = DeleteMetaNodeCommand{} }
func (m *DeleteMetaNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*DeleteMetaNodeCommand) ProtoMessage()               {}
func (*DeleteMetaNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{38} }

func (m *DeleteMetaNodeCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

var E_DeleteMetaNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DeleteMetaNodeCommand)(nil),
	Field:         127,
	Name:          "internal.DeleteMetaNodeCommand.command",
	Tag:           "bytes,127,opt,name=command",
	Filename:      "meta.proto",
}

type DeleteDataNodeCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteDataNodeCommand) Reset()                    { *m = DeleteDataNodeCommand{} }
func (m *DeleteDataNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*DeleteDataNodeCommand) ProtoMessage()               {}
func (*DeleteDataNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{39} }

func (m *DeleteDataNodeCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

var E_DeleteDataNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DeleteDataNodeCommand)(nil),
	Field:         128,
	Name:          "internal.DeleteDataNodeCommand.command",
	Tag:           "bytes,128,opt,name=command",
	Filename:      "meta.proto",
}

type Response struct {
	OK               *bool   `protobuf:"varint,1,req,name=OK" json:"OK,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=Error" json:"Error,omitempty"`
	Index            *uint64 `protobuf:"varint,3,opt,name=Index" json:"Index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{40} }

func (m *Response) GetOK() bool {
	if m != nil && m.OK != nil {
		return *m.OK
	}
	return false
}

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Response) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

// SetMetaNodeCommand is for the initial metanode in a cluster or
// if the single host restarts and its hostname changes, this will update it
type SetMetaNodeCommand struct {
	HTTPAddr         *string `protobuf:"bytes,1,req,name=HTTPAddr" json:"HTTPAddr,omitempty"`
	TCPAddr          *string `protobuf:"bytes,2,req,name=TCPAddr" json:"TCPAddr,omitempty"`
	Rand             *uint64 `protobuf:"varint,3,req,name=Rand" json:"Rand,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetMetaNodeCommand) Reset()                    { *m = SetMetaNodeCommand{} }
func (m *SetMetaNodeCommand) String() string            { return proto.CompactTextString(m) }
func (*SetMetaNodeCommand) ProtoMessage()               {}
func (*SetMetaNodeCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{41} }

func (m *SetMetaNodeCommand) GetHTTPAddr() string {
	if m != nil && m.HTTPAddr != nil {
		return *m.HTTPAddr
	}
	return ""
}

func (m *SetMetaNodeCommand) GetTCPAddr() string {
	if m != nil && m.TCPAddr != nil {
		return *m.TCPAddr
	}
	return ""
}

func (m *SetMetaNodeCommand) GetRand() uint64 {
	if m != nil && m.Rand != nil {
		return *m.Rand
	}
	return 0
}

var E_SetMetaNodeCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*SetMetaNodeCommand)(nil),
	Field:         129,
	Name:          "internal.SetMetaNodeCommand.command",
	Tag:           "bytes,129,opt,name=command",
	Filename:      "meta.proto",
}

type DropShardCommand struct {
	ID               *uint64 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DropShardCommand) Reset()                    { *m = DropShardCommand{} }
func (m *DropShardCommand) String() string            { return proto.CompactTextString(m) }
func (*DropShardCommand) ProtoMessage()               {}
func (*DropShardCommand) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{42} }

func (m *DropShardCommand) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

var E_DropShardCommand_Command = &proto.ExtensionDesc{
	ExtendedType:  (*Command)(nil),
	ExtensionType: (*DropShardCommand)(nil),
	Field:         130,
	Name:          "internal.DropShardCommand.command",
	Tag:           "bytes,130,opt,name=command",
	Filename:      "meta.proto",
}

func init() {
	proto.RegisterType((*Data)(nil), "internal.Data")
	proto.RegisterType((*NodeInfo)(nil), "internal.NodeInfo")
	proto.RegisterType((*DatabaseInfo)(nil), "internal.DatabaseInfo")
	proto.RegisterType((*RetentionPolicySpec)(nil), "internal.RetentionPolicySpec")
	proto.RegisterType((*RetentionPolicyInfo)(nil), "internal.RetentionPolicyInfo")
	proto.RegisterType((*ShardGroupInfo)(nil), "internal.ShardGroupInfo")
	proto.RegisterType((*ShardInfo)(nil), "internal.ShardInfo")
	proto.RegisterType((*SubscriptionInfo)(nil), "internal.SubscriptionInfo")
	proto.RegisterType((*ShardOwner)(nil), "internal.ShardOwner")
	proto.RegisterType((*ContinuousQueryInfo)(nil), "internal.ContinuousQueryInfo")
	proto.RegisterType((*UserInfo)(nil), "internal.UserInfo")
	proto.RegisterType((*UserPrivilege)(nil), "internal.UserPrivilege")
	proto.RegisterType((*Command)(nil), "internal.Command")
	proto.RegisterType((*CreateNodeCommand)(nil), "internal.CreateNodeCommand")
	proto.RegisterType((*DeleteNodeCommand)(nil), "internal.DeleteNodeCommand")
	proto.RegisterType((*CreateDatabaseCommand)(nil), "internal.CreateDatabaseCommand")
	proto.RegisterType((*DropDatabaseCommand)(nil), "internal.DropDatabaseCommand")
	proto.RegisterType((*CreateRetentionPolicyCommand)(nil), "internal.CreateRetentionPolicyCommand")
	proto.RegisterType((*DropRetentionPolicyCommand)(nil), "internal.DropRetentionPolicyCommand")
	proto.RegisterType((*SetDefaultRetentionPolicyCommand)(nil), "internal.SetDefaultRetentionPolicyCommand")
	proto.RegisterType((*UpdateRetentionPolicyCommand)(nil), "internal.UpdateRetentionPolicyCommand")
	proto.RegisterType((*CreateShardGroupCommand)(nil), "internal.CreateShardGroupCommand")
	proto.RegisterType((*DeleteShardGroupCommand)(nil), "internal.DeleteShardGroupCommand")
	proto.RegisterType((*CreateContinuousQueryCommand)(nil), "internal.CreateContinuousQueryCommand")
	proto.RegisterType((*DropContinuousQueryCommand)(nil), "internal.DropContinuousQueryCommand")
	proto.RegisterType((*CreateUserCommand)(nil), "internal.CreateUserCommand")
	proto.RegisterType((*DropUserCommand)(nil), "internal.DropUserCommand")
	proto.RegisterType((*UpdateUserCommand)(nil), "internal.UpdateUserCommand")
	proto.RegisterType((*SetPrivilegeCommand)(nil), "internal.SetPrivilegeCommand")
	proto.RegisterType((*SetDataCommand)(nil), "internal.SetDataCommand")
	proto.RegisterType((*SetAdminPrivilegeCommand)(nil), "internal.SetAdminPrivilegeCommand")
	proto.RegisterType((*UpdateNodeCommand)(nil), "internal.UpdateNodeCommand")
	proto.RegisterType((*CreateSubscriptionCommand)(nil), "internal.CreateSubscriptionCommand")
	proto.RegisterType((*DropSubscriptionCommand)(nil), "internal.DropSubscriptionCommand")
	proto.RegisterType((*RemovePeerCommand)(nil), "internal.RemovePeerCommand")
	proto.RegisterType((*CreateMetaNodeCommand)(nil), "internal.CreateMetaNodeCommand")
	proto.RegisterType((*CreateDataNodeCommand)(nil), "internal.CreateDataNodeCommand")
	proto.RegisterType((*UpdateDataNodeCommand)(nil), "internal.UpdateDataNodeCommand")
	proto.RegisterType((*DeleteMetaNodeCommand)(nil), "internal.DeleteMetaNodeCommand")
	proto.RegisterType((*DeleteDataNodeCommand)(nil), "internal.DeleteDataNodeCommand")
	proto.RegisterType((*Response)(nil), "internal.Response")
	proto.RegisterType((*SetMetaNodeCommand)(nil), "internal.SetMetaNodeCommand")
	proto.RegisterType((*DropShardCommand)(nil), "internal.DropShardCommand")
	proto.RegisterEnum("internal.Command_Type", Command_Type_name, Command_Type_value)
	proto.RegisterExtension(E_CreateNodeCommand_Command)
	proto.RegisterExtension(E_DeleteNodeCommand_Command)
	proto.RegisterExtension(E_CreateDatabaseCommand_Command)
	proto.RegisterExtension(E_DropDatabaseCommand_Command)
	proto.RegisterExtension(E_CreateRetentionPolicyCommand_Command)
	proto.RegisterExtension(E_DropRetentionPolicyCommand_Command)
	proto.RegisterExtension(E_SetDefaultRetentionPolicyCommand_Command)
	proto.RegisterExtension(E_UpdateRetentionPolicyCommand_Command)
	proto.RegisterExtension(E_CreateShardGroupCommand_Command)
	proto.RegisterExtension(E_DeleteShardGroupCommand_Command)
	proto.RegisterExtension(E_CreateContinuousQueryCommand_Command)
	proto.RegisterExtension(E_DropContinuousQueryCommand_Command)
	proto.RegisterExtension(E_CreateUserCommand_Command)
	proto.RegisterExtension(E_DropUserCommand_Command)
	proto.RegisterExtension(E_UpdateUserCommand_Command)
	proto.RegisterExtension(E_SetPrivilegeCommand_Command)
	proto.RegisterExtension(E_SetDataCommand_Command)
	proto.RegisterExtension(E_SetAdminPrivilegeCommand_Command)
	proto.RegisterExtension(E_UpdateNodeCommand_Command)
	proto.RegisterExtension(E_CreateSubscriptionCommand_Command)
	proto.RegisterExtension(E_DropSubscriptionCommand_Command)
	proto.RegisterExtension(E_RemovePeerCommand_Command)
	proto.RegisterExtension(E_CreateMetaNodeCommand_Command)
	proto.RegisterExtension(E_CreateDataNodeCommand_Command)
	proto.RegisterExtension(E_UpdateDataNodeCommand_Command)
	proto.RegisterExtension(E_DeleteMetaNodeCommand_Command)
	proto.RegisterExtension(E_DeleteDataNodeCommand_Command)
	proto.RegisterExtension(E_SetMetaNodeCommand_Command)
	proto.RegisterExtension(E_DropShardCommand_Command)
}

func init() { proto.RegisterFile("meta.proto", fileDescriptorMeta) }

var fileDescriptorMeta = []byte{
	// 1657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xd7, 0xd8, 0x6b, 0xc7, 0x7b, 0x6c, 0x27, 0xf1, 0x38, 0x1f, 0x9b, 0x34, 0xed, 0xdf, 0x9d,
	0xa6, 0x7f, 0x99, 0x22, 0x22, 0x61, 0x15, 0xd4, 0x0b, 0x10, 0x0a, 0x71, 0xdb, 0x04, 0x94, 0x34,
	0xc4, 0xe9, 0x2d, 0x68, 0x6b, 0x4f, 0x9a, 0xa5, 0xf6, 0xee, 0xb2, 0xbb, 0x6e, 0x1b, 0xbe, 0x1a,
	0x40, 0x02, 0x6e, 0x2a, 0x24, 0x24, 0x24, 0x10, 0x77, 0x3c, 0x01, 0x37, 0x3c, 0x00, 0x17, 0x5c,
	0xf0, 0x04, 0x3c, 0x04, 0x2f, 0x81, 0x66, 0xd6, 0xfb, 0x35, 0x3b, 0xbb, 0x9b, 0xf6, 0xce, 0x9e,
	0x73, 0xe6, 0xfc, 0x7e, 0xe7, 0x63, 0xce, 0x9c, 0x59, 0x80, 0x09, 0xf5, 0xf4, 0x2d, 0xdb, 0xb1,
	0x3c, 0x0b, 0xd7, 0x0c, 0xd3, 0xa3, 0x8e, 0xa9, 0x8f, 0xc9, 0x1f, 0x25, 0x50, 0xfa, 0xba, 0xa7,
	0xe3, 0x06, 0x28, 0xc7, 0xd4, 0x99, 0x68, 0xa8, 0x53, 0xea, 0x2a, 0xb8, 0x09, 0x95, 0x3d, 0x73,
	0x44, 0x9f, 0x6a, 0x25, 0xfe, 0xb7, 0x05, 0xea, 0xce, 0x78, 0xea, 0x7a, 0xd4, 0xd9, 0xeb, 0x6b,
	0x65, 0xbe, 0x74, 0x15, 0x2a, 0x07, 0xd6, 0x88, 0xba, 0x9a, 0xd2, 0x29, 0x77, 0xeb, 0x3d, 0xbc,
	0x15, 0x98, 0xdc, 0x62, 0xcb, 0x7b, 0xe6, 0x89, 0x85, 0x5f, 0x01, 0x95, 0x99, 0x7e, 0xa0, 0xbb,
	0xd4, 0xd5, 0x2a, 0x5c, 0x6d, 0x25, 0x52, 0x0b, 0x44, 0x5c, 0xf5, 0x2a, 0x54, 0xee, 0xbb, 0xd4,
	0x71, 0xb5, 0xaa, 0x68, 0x8d, 0x2d, 0x73, 0x95, 0x16, 0xa8, 0xfb, 0xfa, 0x53, 0x6e, 0xbc, 0xaf,
	0xcd, 0x71, 0x0e, 0xab, 0xb0, 0xb0, 0xaf, 0x3f, 0x1d, 0x9c, 0xea, 0xce, 0xe8, 0xae, 0x63, 0x4d,
	0xed, 0xbd, 0xbe, 0x56, 0xe3, 0x02, 0x0c, 0x10, 0x08, 0xf6, 0xfa, 0x9a, 0xca, 0xd7, 0xae, 0xfb,
	0x6c, 0x7c, 0xd2, 0x90, 0x49, 0xfa, 0x3a, 0xa8, 0xfb, 0x34, 0x50, 0xab, 0x67, 0xa9, 0x91, 0x37,
	0xa0, 0x16, 0x6e, 0x01, 0x28, 0xed, 0xf5, 0x67, 0x81, 0x6b, 0x80, 0xb2, 0x6b, 0xb9, 0x1e, 0x8f,
	0x9b, 0x8a, 0x17, 0x60, 0xee, 0x78, 0xe7, 0x90, 0x2f, 0x94, 0x3b, 0xa8, 0xab, 0x92, 0xdf, 0x11,
	0x34, 0x12, 0x8e, 0x37, 0x40, 0x39, 0xd0, 0x27, 0x94, 0xef, 0x56, 0xf1, 0x15, 0x58, 0xe9, 0xd3,
	0x13, 0x7d, 0x3a, 0xf6, 0x8e, 0xa8, 0x47, 0x4d, 0xcf, 0xb0, 0xcc, 0x43, 0x6b, 0x6c, 0x0c, 0xcf,
	0x66, 0xf6, 0x6e, 0x41, 0x2b, 0x29, 0x30, 0xa8, 0xab, 0x95, 0x39, 0xc9, 0xcb, 0x11, 0x49, 0x61,
	0x2f, 0xc7, 0xb9, 0x05, 0xad, 0x1d, 0xcb, 0xf4, 0x0c, 0x73, 0x6a, 0x4d, 0xdd, 0x0f, 0xa6, 0xd4,
	0x31, 0xc2, 0xd4, 0xc5, 0x76, 0x26, 0x55, 0xf8, 0x4e, 0x32, 0x84, 0xb6, 0x60, 0x70, 0x60, 0xd3,
	0x61, 0x8c, 0x38, 0xea, 0xaa, 0x78, 0x11, 0x6a, 0xfd, 0xa9, 0xa3, 0x33, 0x1d, 0xad, 0xd4, 0x41,
	0xdd, 0x32, 0x5e, 0x07, 0x1c, 0x25, 0x26, 0x94, 0x95, 0xb9, 0x6c, 0x11, 0x6a, 0x47, 0xd4, 0x1e,
	0x1b, 0x43, 0xfd, 0x40, 0x53, 0x3a, 0xa8, 0xdb, 0x24, 0x7f, 0xa1, 0x14, 0x8a, 0x24, 0x3c, 0x49,
	0x94, 0x52, 0x0e, 0x4a, 0x29, 0x85, 0x52, 0xea, 0x36, 0xf1, 0x6b, 0x50, 0x8f, 0xb4, 0x83, 0x92,
	0xd4, 0x22, 0xf7, 0x63, 0x95, 0xc4, 0xc0, 0x5f, 0x87, 0xe6, 0x60, 0xfa, 0xc0, 0x1d, 0x3a, 0x86,
	0xcd, 0xcc, 0x06, 0xc5, 0xb9, 0x1e, 0xdb, 0x10, 0x13, 0xf3, 0x60, 0x3d, 0x47, 0x30, 0x2f, 0x58,
	0x89, 0x57, 0x47, 0x0b, 0xd4, 0x81, 0xa7, 0x3b, 0xde, 0xb1, 0x31, 0xa1, 0x33, 0x0f, 0x16, 0x60,
	0xee, 0xb6, 0x39, 0xe2, 0x0b, 0x3e, 0xed, 0x16, 0xa8, 0x7d, 0x3a, 0xa6, 0x1e, 0x1d, 0x6d, 0x7b,
	0x9c, 0x77, 0x19, 0x5f, 0x83, 0x2a, 0x37, 0x1a, 0x50, 0x6e, 0x0b, 0x94, 0x39, 0x4e, 0x1b, 0xea,
	0xc7, 0xce, 0xd4, 0x1c, 0xea, 0xfe, 0xce, 0x2a, 0x8b, 0x34, 0x19, 0x80, 0x1a, 0x69, 0xc4, 0x99,
	0x2c, 0x41, 0xed, 0xde, 0x13, 0x93, 0x9d, 0x67, 0x57, 0x2b, 0x75, 0xca, 0x5d, 0xe5, 0xdd, 0x92,
	0x86, 0xf0, 0x26, 0x54, 0xf9, 0x6a, 0x50, 0x54, 0x4b, 0x02, 0x10, 0x17, 0x92, 0x3e, 0x2c, 0x8a,
	0x8e, 0x0b, 0x89, 0x6a, 0x80, 0xb2, 0x6f, 0x8d, 0xe8, 0xac, 0x6a, 0x97, 0xa0, 0xd1, 0xa7, 0xae,
	0x67, 0x98, 0xba, 0x1f, 0x46, 0x66, 0x5b, 0x25, 0x1b, 0x00, 0x91, 0x4d, 0x3c, 0x0f, 0xd5, 0xd9,
	0xd1, 0xe6, 0xfc, 0x48, 0x0f, 0xda, 0x92, 0x62, 0x14, 0x60, 0x9a, 0x50, 0xe1, 0x22, 0x1f, 0x87,
	0x3c, 0x80, 0x5a, 0xd8, 0x2d, 0x52, 0x7c, 0x76, 0x75, 0xf7, 0x74, 0xc6, 0xa7, 0x09, 0x95, 0xed,
	0xd1, 0xc4, 0xf0, 0xeb, 0xa4, 0x86, 0x5f, 0x05, 0x38, 0x74, 0x8c, 0xc7, 0xc6, 0x98, 0x3e, 0x0c,
	0xcf, 0xc4, 0x6a, 0xb2, 0x01, 0x85, 0x72, 0x72, 0x13, 0x9a, 0x89, 0x05, 0x5e, 0x93, 0xb3, 0x03,
	0x3d, 0x03, 0x6b, 0x81, 0x1a, 0x8a, 0x39, 0x62, 0x85, 0xfc, 0x53, 0x85, 0xb9, 0x1d, 0x6b, 0x32,
	0xd1, 0xcd, 0x11, 0xde, 0x04, 0xc5, 0x3b, 0xb3, 0x7d, 0xe5, 0xf9, 0x78, 0x43, 0x9c, 0x29, 0x6c,
	0x1d, 0x9f, 0xd9, 0x94, 0xfc, 0x5a, 0x05, 0x85, 0xfd, 0xc0, 0xcb, 0xd0, 0xda, 0x71, 0xa8, 0xee,
	0x51, 0x16, 0x9e, 0x99, 0xca, 0x22, 0x62, 0xcb, 0x7e, 0x95, 0xc4, 0x97, 0x4b, 0x78, 0x0d, 0x96,
	0x7d, 0xed, 0x80, 0x53, 0x20, 0x2a, 0xe3, 0x55, 0x68, 0xf7, 0x1d, 0xcb, 0x16, 0x05, 0x0a, 0xee,
	0xc0, 0x86, 0xbf, 0x47, 0x38, 0x80, 0x81, 0x46, 0x05, 0x5f, 0x81, 0x75, 0xb6, 0x35, 0x43, 0x5e,
	0xc5, 0x9b, 0xd0, 0x19, 0x50, 0x4f, 0xde, 0xb9, 0x02, 0xad, 0x39, 0x86, 0x73, 0xdf, 0x1e, 0x65,
	0xe3, 0xd4, 0xf0, 0x25, 0x58, 0xf5, 0x99, 0x44, 0x47, 0x28, 0x10, 0xaa, 0x4c, 0xe8, 0x7b, 0x9c,
	0x16, 0x42, 0xe4, 0x83, 0x50, 0x34, 0x81, 0x46, 0x3d, 0xf0, 0x21, 0x43, 0xde, 0x88, 0xe2, 0xcc,
	0xd2, 0x1b, 0x2c, 0x37, 0x71, 0x1b, 0x16, 0xd8, 0xb6, 0xf8, 0xe2, 0x3c, 0xd3, 0xf5, 0x3d, 0x89,
	0x2f, 0x2f, 0xb0, 0x08, 0x0f, 0xa8, 0x17, 0xe6, 0x3e, 0x10, 0x2c, 0x62, 0x0c, 0xf3, 0x2c, 0x3e,
	0xba, 0xa7, 0x07, 0x6b, 0x2d, 0xbc, 0x01, 0xda, 0x80, 0x7a, 0xbc, 0x0e, 0x53, 0x3b, 0x70, 0x84,
	0x10, 0x4f, 0x6f, 0x1b, 0x5f, 0x86, 0xb5, 0x59, 0x80, 0x62, 0xe7, 0x2f, 0x10, 0x2f, 0xf3, 0x10,
	0x39, 0x96, 0x2d, 0x13, 0xae, 0x30, 0x93, 0x47, 0x74, 0x62, 0x3d, 0xa6, 0x87, 0x34, 0x22, 0xbd,
	0x1a, 0x55, 0x4c, 0x70, 0xeb, 0x05, 0x22, 0x2d, 0x59, 0x4c, 0x71, 0xd1, 0x1a, 0x13, 0xf9, 0xfc,
	0x44, 0xd1, 0x3a, 0x13, 0xf9, 0x79, 0x12, 0x0d, 0x5e, 0x8a, 0x44, 0xe2, 0xae, 0x0d, 0xbc, 0x02,
	0x78, 0x40, 0x3d, 0x71, 0xcb, 0x65, 0xbc, 0x04, 0x8b, 0xdc, 0x25, 0x96, 0xf3, 0x60, 0xf5, 0xca,
	0x8d, 0x5a, 0x6d, 0xb4, 0x78, 0x7e, 0x7e, 0x7e, 0x5e, 0x22, 0xb6, 0xe4, 0x78, 0x84, 0x97, 0x70,
	0x78, 0xf8, 0x8f, 0x74, 0x73, 0xe4, 0x8f, 0x32, 0xbd, 0x77, 0x60, 0x6e, 0x38, 0x53, 0x6b, 0xa5,
	0xce, 0x9e, 0x46, 0x3b, 0xa8, 0x5b, 0xef, 0x5d, 0x8a, 0x09, 0x44, 0xe3, 0xc4, 0x92, 0x9c, 0xbc,
	0x44, 0x6b, 0x6d, 0x42, 0xe5, 0x8e, 0xe5, 0x0c, 0xfd, 0xb3, 0x5f, 0x2b, 0x00, 0x3c, 0x11, 0x01,
	0x53, 0xb6, 0xc9, 0x6f, 0x28, 0xe3, 0x50, 0x0b, 0x4d, 0xee, 0x4d, 0x58, 0x48, 0x4f, 0x0d, 0xa8,
	0x70, 0x34, 0xe8, 0xed, 0xe4, 0x12, 0x7c, 0xc8, 0x4d, 0xfc, 0x4f, 0x8c, 0x88, 0x40, 0x85, 0x9c,
	0x48, 0xbb, 0x4b, 0x92, 0x61, 0x6f, 0x3b, 0x17, 0xe9, 0x54, 0x24, 0x2b, 0x31, 0x48, 0xfe, 0x46,
	0xf9, 0xdd, 0x4a, 0xd2, 0x8f, 0xa5, 0x71, 0x29, 0x15, 0x8f, 0x4c, 0x6d, 0xa8, 0xef, 0xeb, 0x8f,
	0xe8, 0xac, 0xad, 0xf9, 0x97, 0x45, 0xef, 0xbd, 0x5c, 0x17, 0x0c, 0xee, 0xc2, 0xff, 0xc5, 0x60,
	0xc9, 0xa9, 0x92, 0x6f, 0x51, 0x5e, 0x5f, 0x95, 0x78, 0x12, 0x44, 0x93, 0x5f, 0x63, 0xbd, 0xdd,
	0x5c, 0x2a, 0x1f, 0x73, 0x2a, 0x9b, 0xc9, 0x68, 0x66, 0x10, 0xf9, 0x11, 0x15, 0x37, 0xf0, 0x42,
	0x3a, 0x07, 0xb9, 0x74, 0x1e, 0x71, 0x3a, 0x37, 0x62, 0xf3, 0x44, 0x01, 0x1e, 0xf9, 0x17, 0xe5,
	0xdf, 0x17, 0x45, 0x84, 0xd8, 0x64, 0x75, 0x40, 0x9f, 0xf0, 0x85, 0x72, 0x6a, 0x48, 0x55, 0x52,
	0x83, 0x68, 0x85, 0x0d, 0xa2, 0x62, 0xd2, 0xd9, 0x14, 0x55, 0xc3, 0xcb, 0xd0, 0xe4, 0x0d, 0x28,
	0xdc, 0x3d, 0xc7, 0x76, 0x17, 0xd4, 0xc2, 0x58, 0xac, 0x85, 0x3c, 0x67, 0xc8, 0x4f, 0x28, 0xf3,
	0xee, 0x93, 0x38, 0x3a, 0x0f, 0xd5, 0xc4, 0xbb, 0xa0, 0x05, 0x2a, 0x9b, 0x20, 0x5d, 0x4f, 0x9f,
	0xd8, 0xfe, 0x18, 0xd9, 0xbb, 0x9d, 0x4b, 0x6e, 0xc2, 0xc9, 0x5d, 0x15, 0x0b, 0x35, 0x85, 0x4d,
	0x7e, 0x46, 0x99, 0xd7, 0xee, 0x05, 0x78, 0x2d, 0x41, 0x23, 0xf1, 0x3a, 0xe3, 0x4f, 0xc7, 0x02,
	0x6a, 0xa6, 0x48, 0x2d, 0x03, 0x9e, 0xfc, 0x82, 0xf2, 0x2f, 0xfd, 0xc2, 0x02, 0x09, 0xc7, 0xc7,
	0x32, 0x2f, 0xe0, 0xfc, 0x74, 0x5a, 0xf2, 0xa3, 0x2d, 0x87, 0x0e, 0x8f, 0xf6, 0xcb, 0x31, 0x2b,
	0x38, 0xda, 0xb6, 0xec, 0x68, 0x67, 0x10, 0x79, 0x26, 0x19, 0x6b, 0x5e, 0x60, 0x38, 0x2e, 0xb8,
	0xbd, 0x3e, 0x91, 0x5f, 0x97, 0x31, 0x2c, 0xf2, 0x61, 0x6a, 0x80, 0x12, 0x2e, 0x85, 0xb7, 0x73,
	0x11, 0x1c, 0x8e, 0xb0, 0x96, 0xf4, 0x35, 0x6e, 0xdf, 0x96, 0xcc, 0x62, 0x79, 0x0e, 0x16, 0x78,
	0xe4, 0x8a, 0x1e, 0xa5, 0x8c, 0x93, 0x1f, 0x90, 0x74, 0xce, 0x63, 0x49, 0x65, 0x6a, 0x66, 0xf2,
	0xbd, 0x1a, 0xa4, 0xb9, 0x94, 0x7e, 0x1b, 0xb0, 0x08, 0x57, 0x0a, 0x2e, 0x45, 0x4f, 0xbc, 0x14,
	0x25, 0xc8, 0x64, 0x2c, 0xce, 0x97, 0x78, 0xc3, 0xff, 0xaa, 0xc3, 0x79, 0xd4, 0x7b, 0xf3, 0xc9,
	0xaf, 0x2e, 0xbd, 0xb7, 0x72, 0x21, 0xa7, 0x1c, 0x52, 0x4b, 0xb6, 0xea, 0xc8, 0x36, 0xf9, 0x06,
	0x65, 0x8f, 0xae, 0x92, 0x20, 0x84, 0x05, 0xe5, 0x8f, 0x43, 0x77, 0x72, 0xb1, 0x1f, 0x73, 0x6c,
	0x92, 0xc0, 0x96, 0x02, 0x11, 0x53, 0x32, 0x21, 0x67, 0x7f, 0x89, 0x29, 0xc8, 0xfa, 0x13, 0x79,
	0xd6, 0xe3, 0x53, 0xd8, 0x9f, 0x28, 0x67, 0xf6, 0x96, 0x7c, 0xa7, 0x48, 0xe6, 0x7d, 0x35, 0x3d,
	0x83, 0x94, 0x13, 0x2f, 0x65, 0x45, 0xfa, 0x52, 0x66, 0xcf, 0x7d, 0xb5, 0x77, 0x37, 0x97, 0xfb,
	0x19, 0xe7, 0x7e, 0x2d, 0xd5, 0xca, 0xd3, 0x2c, 0x59, 0xc7, 0xcc, 0x7a, 0x20, 0xbc, 0xb4, 0x07,
	0x05, 0xdd, 0xfc, 0xd3, 0x54, 0x37, 0x97, 0xe3, 0xb3, 0x7c, 0xa6, 0x9e, 0x27, 0x61, 0x3e, 0x91,
	0x9f, 0xcf, 0xed, 0xd1, 0xc8, 0xb9, 0x50, 0x3e, 0x3f, 0x13, 0xf3, 0x99, 0x32, 0x4d, 0x9e, 0xa3,
	0x8c, 0x87, 0x0f, 0xf3, 0x7d, 0xf7, 0xf8, 0xf8, 0x90, 0x83, 0xa1, 0xd8, 0x67, 0xbc, 0x08, 0x3d,
	0x7c, 0x52, 0xf8, 0xf7, 0x59, 0xfe, 0x00, 0xfd, 0xb9, 0x7c, 0x80, 0x16, 0x50, 0xc9, 0xb3, 0x8c,
	0xc7, 0xd6, 0x05, 0xe8, 0x14, 0x10, 0xf8, 0x22, 0x7b, 0x82, 0x8f, 0x13, 0xf8, 0x0e, 0x65, 0xbc,
	0xe9, 0x2e, 0xfa, 0x7d, 0xb3, 0x98, 0xc9, 0x97, 0x22, 0x13, 0x29, 0x1e, 0x39, 0xcd, 0x78, 0x41,
	0xc6, 0x89, 0x14, 0x20, 0x3d, 0x13, 0x91, 0xa4, 0x06, 0x89, 0x91, 0xf1, 0x20, 0x4d, 0x20, 0xf5,
	0x73, 0x91, 0xce, 0x91, 0x1c, 0x4a, 0x74, 0xea, 0x26, 0x1b, 0x35, 0x5d, 0xdb, 0x32, 0x5d, 0xca,
	0xac, 0xdf, 0x7b, 0x9f, 0x5b, 0xaf, 0xb1, 0xf6, 0x78, 0xdb, 0x71, 0x2c, 0x87, 0xbf, 0xd5, 0xd4,
	0xe8, 0xc3, 0x3b, 0x1b, 0x59, 0x15, 0xf2, 0x3d, 0x92, 0xbd, 0x8b, 0x5f, 0xbc, 0x44, 0xf3, 0x2f,
	0x99, 0xaf, 0x7c, 0x1f, 0x36, 0x12, 0x6d, 0x57, 0x8c, 0xd5, 0x47, 0xe9, 0x97, 0x78, 0x22, 0x4c,
	0xf9, 0x27, 0xf2, 0x6b, 0x1f, 0x62, 0x5d, 0x68, 0x04, 0x31, 0x63, 0xff, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xc6, 0x36, 0x96, 0x84, 0xa1, 0x18, 0x00, 0x00,
}
